{
  lib,
  helpers,
  config,
  icons,
  pkgs,
  ...
}:
let

in
{
  extraPlugins = with pkgs.vimPlugins; [
    edge
    unicode-vim
    lualine-lsp-progress
  ];

  # based on {https://github.com/r17x/nixpkgs/blob/main/configs/nvim/lua/config/nvim-tree.lua}
  plugins.nvim-tree.enable = true;
  plugins.nvim-tree.disableNetrw = true;
  plugins.nvim-tree.view.side = "left";
  plugins.nvim-tree.view.width = 25;
  plugins.nvim-tree.respectBufCwd = true;
  plugins.nvim-tree.autoReloadOnWrite = true;
  plugins.nvim-tree.git.enable = true;
  plugins.nvim-tree.filters.dotfiles = true;
  plugins.nvim-tree.renderer.highlightGit = true;
  plugins.nvim-tree.renderer.indentMarkers.enable = true;

  extraConfigLua = # lua
    ''
      -- enable elite mode
      vim.g.elite_mode = 1

      vim.opt.list = true
      vim.opt.listchars:append("eol:↴")

      -- treesitter folding
      vim.cmd [[ set nofoldenable ]]
    '';

  plugins.treesitter.enable = true;
  plugins.treesitter.folding = true;
  plugins.treesitter.indent = true;
  plugins.treesitter.nixvimInjections = true;
  plugins.treesitter.grammarPackages = builtins.map (
    x: pkgs.vimPlugins.nvim-treesitter.builtGrammars.${x}
  ) config.plugins.treesitter.ensureInstalled;
  plugins.treesitter.ignoreInstall = [
    # ┌─────────────────────────────────────┐
    # │ move to ensureInstalled for enabled │
    # └─────────────────────────────────────┘
    "ada"
    "agda"
    "angular"
    "apex"
    "arduino"
    "astro"
    "authzed"
    "awk"
    "bass"
    "beancount"
    "bibtex"
    "bicep"
    "bitbake"
    "blueprint"
    "c_sharp"
    "cairo"
    "capnp"
    "chatito"
    "clojure"
    "commonlisp"
    "cooklang"
    "corn"
    "cpon"
    "cpp"
    "csv"
    "cuda"
    "cue"
    "d"
    "dart"
    "devicetree"
    "disassembly"
    "djot"
    "doxygen"
    "dtd"
    "earthfile"
    "ebnf"
    "eds"
    "eex"
    "elixir"
    "elm"
    "elsa"
    "elvish"
    "embedded_template"
    "erlang"
    "facility"
    "faust"
    "fennel"
    "fidl"
    "firrtl"
    "foam"
    "forth"
    "fortran"
    "fsh"
    "func"
    "fusion"
    "gdscript"
    "gdshader"
    "gleam"
    "glimmer"
    "glsl"
    "gn"
    "gnuplot"
    "godot_resource"
    "gowork"
    "groovy"
    "gstlaunch"
    "hack"
    "hare"
    "heex"
    "hjson"
    "hlsl"
    "hlsplaylist"
    "hocon"
    "hoon"
    "htmldjango"
    "hurl"
    "hyprlang"
    "idl"
    "ini"
    "inko"
    "ispc"
    "janet_simple"
    "java"
    "json5"
    "jsonc"
    "jsonnet"
    "julia"
    "just"
    "kconfig"
    "kdl"
    "kotlin"
    "koto"
    "kusto"
    "lalrpop"
    "ledger"
    "leo"
    "linkerscript"
    "liquid"
    "liquidsoap"
    "llvm"
    "m68k"
    "matlab"
    "menhir"
    "meson"
    "mlir"
    "muttrc"
    "nasm"
    "nickel"
    "nim"
    "nim_format_string"
    "ninja"
    "nqc"
    "objc"
    "objdump"
    "odin"
    "org"
    "pascal"
    "pem"
    "perl"
    "php"
    "php_only"
    "phpdoc"
    "pioasm"
    "pod"
    "poe_filter"
    "pony"
    "printf"
    "prisma"
    "promql"
    "properties"
    "prql"
    "psv"
    "pug"
    "puppet"
    "purescript"
    "ql"
    "qmldir"
    "qmljs"
    "r"
    "racket"
    "rasi"
    "rbs"
    "re2c"
    "readline"
    "rego"
    "requirements"
    "rnoweb"
    "robot"
    "roc"
    "ron"
    "rst"
    "ruby"
    "scala"
    "scfg"
    "scheme"
    "scss"
    "slang"
    "slint"
    "smali"
    "smithy"
    "snakemake"
    "solidity"
    "soql"
    "sosl"
    "sourcepawn"
    "sparql"
    "squirrel"
    "starlark"
    "strace"
    "styled"
    "supercollider"
    "surface"
    "svelte"
    "swift"
    "sxhkdrc"
    "systemtap"
    "t32"
    "tablegen"
    "tact"
    "tcl"
    "teal"
    "thrift"
    "tiger"
    "tlaplus"
    "tsv"
    "turtle"
    "twig"
    "typespec"
    "typoscript"
    "typst"
    "udev"
    "ungrammar"
    "unison"
    "usd"
    "uxntal"
    "v"
    "vala"
    "vento"
    "verilog"
    "vue"
    "wgsl"
    "wgsl_bevy"
    "wing"
    "wit"
    "xcompose"
    "yang"
    "yuck"
    "zathurarc"
    "zig"
  ];
  plugins.treesitter.ensureInstalled = [
    # ┌────────────────────────────────────┐
    # │ move to ignoreInstall for disabled │
    # └────────────────────────────────────┘
    "asm"
    "bash"
    "c"
    "cmake"
    "comment"
    "css"
    "dhall"
    "diff"
    "dockerfile"
    "dot"
    "fish"
    "git_config"
    "git_rebase"
    "gitattributes"
    "gitcommit"
    "gitignore"
    "go"
    "gomod"
    "gosum"
    "gotmpl"
    "gpg"
    "graphql"
    "haskell"
    "haskell_persistent"
    "hcl"
    "helm"
    "html"
    "http"
    "javascript"
    "jq"
    "jsdoc"
    "json"
    "latex"
    "lua"
    "luadoc"
    "luap"
    "luau"
    "make"
    "markdown"
    "markdown_inline"
    "mermaid"
    "nix"
    "norg"
    "ocaml"
    "ocaml_interface"
    "ocamllex"
    "passwd"
    "po"
    "proto"
    "pymanifest"
    "python"
    "query"
    "regex"
    "rust"
    # "rescript"
    "sql"
    "ssh_config"
    "templ"
    "terraform"
    "textproto"
    "tmux"
    "todotxt"
    "toml"
    "tsx"
    "typescript"
    "vhs"
    "vim"
    "vimdoc"
    "xml"
    "yaml"
  ];

}
